# Generated by Django 3.1 on 2020-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=20)),
                ('normal', models.CharField(max_length=500)),
                ('abnormal', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
