# Generated by Django 3.1 on 2020-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scraped_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='abnormal',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reports',
            name='normal',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reports',
            name='notes',
            field=models.CharField(max_length=1000),
        ),
    ]
