# Generated by Django 3.0.8 on 2020-08-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200827_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='abnormal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='normal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='notes',
            field=models.TextField(),
        ),
    ]
