# Generated by Django 3.1 on 2020-09-06 20:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200827_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='abnormal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reports',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reports',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reports',
            name='normal',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
