# Generated by Django 3.1 on 2020-09-06 20:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200907_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='abnormal',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reports',
            name='notes',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
