# Generated by Django 3.1 on 2020-09-06 20:56

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200907_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='abnormal',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='notes',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
