# Generated by Django 3.1 on 2020-09-16 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200907_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='notes',
        ),
        migrations.AddField(
            model_name='reports',
            name='file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
