# Generated by Django 3.1 on 2020-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200916_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
