# Generated by Django 3.1 on 2020-09-16 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200916_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
