# Generated by Django 3.1.2 on 2020-11-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200916_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='abnormal',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='reports',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reports',
            name='birthday',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reports',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reports',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
