# Generated by Django 3.1 on 2020-12-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='imgpath',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
