# Generated by Django 3.1.5 on 2021-02-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_patient_imgpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('user_role', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
