# Generated by Django 3.1.5 on 2021-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=10)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='patient_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('symptom', models.CharField(blank=True, max_length=1000)),
                ('prescription', models.CharField(blank=True, max_length=1000)),
                ('summary', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='patient_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
