# Generated by Django 3.1.5 on 2021-03-29 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_history',
            name='summary',
        ),
        migrations.AddField(
            model_name='patient_history',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='prescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='symptom',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
