# Generated by Django 3.1.5 on 2021-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210329_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
